# vim:ft=kitty

## name:     Ayu Dark
## upstream: https://github.com/ayu-theme/ayu-colors

# The basic colors
foreground              #BFBDB6
background              #0B0E14
selection_foreground    #0B0E14
selection_background    #E6B450

# Cursor colors
cursor                  #E6B450
cursor_text_color       #0B0E14

# URL underline color when hovering with mouse
url_color               #59C2FF

# Kitty window border colors
active_border_color     #E6B450
inactive_border_color   #565B66
bell_border_color       #FF8F40

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0B0E14
active_tab_background   #E6B450
inactive_tab_foreground #BFBDB6
inactive_tab_background #131721
tab_bar_background      #0B0E14

# Colors for marks (marked text in the terminal)
mark1_foreground #0B0E14
mark1_background #59C2FF
mark2_foreground #0B0E14
mark2_background #D2A6FF
mark3_foreground #0B0E14
mark3_background #95E6CB

# The 16 terminal colors

# black
color0 #11151C
color8 #686868

# red
color1 #EA6C73
color9 #F07178

# green
color2  #7FD962
color10 #AAD94C

# yellow
color3  #F9AF4F
color11 #FFB454

# blue
color4  #53BDFA
color12 #59C2FF

# magenta
color5  #CDA1FA
color13 #D2A6FF

# cyan
color6  #90E1C6
color14 #95E6CB

# white
color7  #C7C7C7
color15 #FFFFFF
