icons_format = "{icon}"

[theme]
theme = "ctp-latte"

[theme.overrides]
separator = "|"
separator_bg = "#eff1f5"
separator_fg = "#4c4f69"
idle_bg = "#eff1f5"


[icons]
icons = "awesome4"

[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

# https://fontawesome.com/v4/cheatsheet/
cpu = "\uf2db" # fa-microchip
memory_mem = "\uf1c0" # fa-database
memory_swap = "\uf0dc" # fa-sort
time = "\uf133" # fa-calendar-o


[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = "$icon $utilization"

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:2)/$mem_total.eng(w:2)"
format_alt = "$icon_swap $swap_free.eng(w:2)/$swap_free.eng(w:2)"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available.eng(w:2)"

[[block]]
block = "sound"
format = "$icon $volume"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%A %d-%m-%y %R') "

